config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/', to: 'static_pages#home', as: 'home'
  #get '/welcome/:first_name', to: 'static_pages#welcome', as: 'welcoming'
  #get '/team', to: 'static_pages#team'
  #get '/contact', to: 'static_pages#contact'
  #get '/:potin', to: 'static_pages#potin', as: 'potin'

  resources :welcomes
  resources :teams, only: (:index)
  resources :contacts, only: (:index)
  resources :users, only: [:show, :new, :create]
  resources :gossips
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, 
		presence: true
	validates :zip_code, 
		presence: true,
		uniqueness: true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..14 }
	validates :content, presence: true

	belongs_to :user
	has_many :gossip_tags, dependent: :destroy
	has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :gossip 
	belongs_to :tag 
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip_tags, dependent: :destroy
	has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :password, presence: true, length:{minimum: 6}

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :description, presence: true
	validates :email, presence: true, uniqueness: true,
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	validates :age, presence: true

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 	add_flash_types :alert, :danger, :info, :error, :warning
    include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	
	def show
		@id = params[:id]
		@city = City.find(params[:id])
		@user_city = @city.name
	end
	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index

	end


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all 
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60


   # binding.pry
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id:11)

    if @gossip.save
      redirect_to gossips_path, notice: "Potin sauvegardé, merci pour ta contribution !"
      puts "Potin sauvegardé"
    else
      puts "La sauvegarde n'a pu être faite. Voici pourquoi :"
      puts @gossip.errors.messages
     render'new', alert: "Le potin n'a pu être sauvegardé, vois pourquoi ds la notification."
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params)
    redirect_to gossips_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    session = User.new
  end
  
  def create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gossips_path
    else
      flash.now[:danger] = 'Combinaison email/mot de passe invalide !'
      render 'new'
    end
  end

  def destroy
    if session.delete(:user_id)
      flash[:danger] = 'Au revoir !'
      redirect_to gossips_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home

	end
	
	def team

	end

	def contact

	end

	def welcome
    	@first_name_user = params[:first_name]
  	end

  	def potin 
  		@chosen_gossip = params[:potin]
  	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

	def index

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new 
	end

	def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60


   # binding.pry
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: params[:city_id], password: params[:password])

    if @user.save
    	puts "Utilisateur sauvegardé"	
      redirect_to gossips_path, notice: "Profil créé, tu vas pouvoir rapporter de nouveaux potins !"
      
    else
      puts "Nous n'avons pas pu créer ton profil. Voici pourquoi :"
      puts @user.errors.messages
     render'new', alert: "Ton profil utilisateur n'a pas pu être sauvegardé, vois pourquoi ds la notification."
    end

  end

	def show
		@user = User.find(params[:id])
		@author_info = Gossip.find(params[:id]).user
		@user_city = @author_info.city.name 
	end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

	def show
		@first_name = params[:first_name]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
    
    def logged_in?
        if session[:user_id].nil?
            return true
        else 
            return false
        end
    end

    def good_user?
        if session[:user_id] == Gossip.find(params[:id]).user_id
            return true
        else
            return false
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/index.html.erb
<h1><%= @city.name %></h1> 

<p> Les potins lies a la ville sont les suivants </p>] 

<div class="card-columns">
  <% @gossips.each do |gossip|%>
    <div class="card" style="max-width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> Title : <%= gossip.title %></h5> 
        <p class="card-text"><small class="text-muted"> Author <%= gossip.user.first_name %></small></p>
        <%= link_to "voir le gossip", gossip_path(gossip.id), class:"btn btn-primary" %>
        <%= link_to "Editer le gossip", edit_gossip_path(gossip.id), class:"btn btn-default" %>
        <a href="<%=  gossip_path(gossip.id) %>" class="btn btn-danger"  data-confirm="etes-vous surs ?" data-method="DELETE"> Supprimer </a>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/edit.html.erb
<h1> Editer le gossip <%= @gossip.title %></h1> 

<!-- ... -->

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= f.text_field :title, class: 'form-control' %>
    <br /> <br />
  </div>

  <div class="form-group">
    <%= label_tag 'Contenu' %>
    <%= f.text_area :content,  class: 'form-control' %>
    <br /> <br />
  </div>

  <div class="form-group">
    <%= submit_tag "Edit Gossip", class:'btn btn-primary' %>
    </div>
<% end %>

<!-- ... -->

<% if @gossip.errors.any? %>
<p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
<ul>
  <% @gossip.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/gossips/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Bienvenue sur The Gossip Project !</h1>
  <p class="lead">Il s'agit d'un projet de création de potins - ce projet est évolutif, et sera amélioré au fil des jours. Merci de le consulter régulièrement pour constater les améliorations, et surtout, pour faire de nouvelles contributions de potins !</p>
  <hr class="my-4">
  <p>Nous t'invitons dès maintenant à déposer ta contribution, en déposant un nouveau potin en cliquant sur le bouton ci-dessous.</p>
  <%= link_to "Création d'un nouveau potin", new_gossip_path, class: "btn btn-primary btn-lg" %>
</div>


<h2>  Voici la liste des potins :</h2>
<div class="card-columns">
    <% @gossips.each do |gossip| %>   
        <div class="card">
            <div class="card-body">
            <h5 class="card-title"> Titre : <%= gossip.title %></h5>
            <p class="card-text"> Auteur : <%= gossip.user.first_name %></p>
            <%= link_to "Voir le potin", gossip_path(gossip.id), class: "btn btn-primary" %>
            <%= link_to "Editer le gossip", edit_gossip_path(gossip.id), class:"btn btn-default" %>
        	<a href="<%=  gossip_path(gossip.id) %>" class="btn btn-danger"  data-confirm="Etes-vous surs de vouloir supprimer le gossip ?" data-method="DELETE"> Supprimer </a>
            </div>
        </div>        
    <% end %>
</div>

app/views/gossips/new.html.erb
<div class="card">
  <div class="card-body">

  <h1>Formulaire de création d'un nouveau potin</h1>

    <%= form_tag gossips_path(action: 'create'), method: "post" do %>

      <%= label_tag 'Titre' %></br>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu' %></br>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Creation du potin" %>

    <% end %>

      </br>

      <% if @gossip.errors.any? %>
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
          <ul>
            <% @gossip.errors.full_messages.each do |message| %>
              <div class="alert alert-danger" role="alert">
              <li><%= message %></li>
              </div>
            <% end %>
            
          </ul>

      <% end %>

  </div>
</div>

app/views/gossips/show.html.erb
<h1>Voici les détails du potin numéro : <%= @gossip.id %>  </h1>

<div class="card" style="width: 36rem;">
  <div class="card-body">
    <h5 class="card-title"> Titre : <%= @gossip.title %></h5>
    <p class="card-text"> Contenu : <%= @gossip.content %></p>
    <h6 class="card-subtitle mb-2 text-muted"> Auteur : <%= @gossip.user.first_name %></h6>
    <%= link_to "Voir l'auteur", user_path, class:"btn btn-primary" %>
    <h6></h6>
    <h6 class="card-subtitle mb-2 text-muted"> Ville : <%= @gossip.user.city.name %></h6>
 	<%= link_to "Voir les potins de sa ville", city_path, class:"btn btn-primary" %>
 	<h6></h6>
 	<h6 class="card-subtitle mb-2 text-muted"> Créé le : <%= @gossip.created_at %></h6>

  </div>
</div>

<%= link_to "Pour revenir à la page d'accueil", gossips_path, class:"btn btn-primary" %>

app/views/static_pages/contact.html.erb
<h1>Pour nous contacter</h1>
<p>Rendez-vous dans app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur The Gossip Project !</h1>

<div>
    <%= link_to "As tu un nouveau potin à raconter?", new_gossip_path %>
</div>

<h2>Voici la liste des potins :</h2>
<div class="card-columns">
    <% Gossip.count.times do |i| %>   
        <div class="card">
            <div class="card-body">
            <h5 class="card-title"><%= Gossip.find(i + 1).user.first_name %></h5>
            <p class="card-text"><%= Gossip.find(i + 1).title %></p>
            </div>
        </div>        
    <% end %>
</div>

app/views/static_pages/potin.html.erb
<h1>Voici les détails du potin numéro : <%= @chosen_gossip %>  </h1>

<p>Son titre : <%= Gossip.find(@chosen_gossip).title %></p>

<p>Son auteur : <%= Gossip.find(@chosen_gossip).user.first_name %></p>

<p>Son contenu : <%= Gossip.find(@chosen_gossip).content %></p>

<p>Il a été créé le : <%= Gossip.find(@chosen_gossip).created_at %></p>

app/views/static_pages/team.html.erb
<h1>Voici notre équipe pour ce projet</h1>
<p>L'équipe est composée de moi-même et du support du groupe</p>

app/views/static_pages/welcome.html.erb
<h1>Bienvenue <%= @first_name_user %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non?</p>

app/views/users/new.html.erb
<div class="card">
  <div class="card-body">
  
    <h1>Formulaire de création d'un nouvel utilisateur </h1>
    </br>

    <%= form_tag users_path(action: "create"), method: "post" do %>

        <%= label_tag "Prénom:" %></br>
        <%= text_field_tag "first_name", @first_name %>
        <br /> <br />

        <%= label_tag "Nom:" %></br>
        <%= text_field_tag "last_name", @last_name %>
        <br /> <br />

        <%= label_tag "Description:" %></br>
        <%= text_area_tag "description", @description %>
        <br /> <br />

        <%= label_tag "email:" %></br>
        <%= text_field_tag "email", @email %>
        <br /> <br />

        <%= label_tag "age:" %></br>
        <%= text_field_tag "age", @age.to_i %>
        <br /> <br />

        <%= label_tag "choisi un numéro de ville entre 1 et 10:" %></br>
        <%= text_field_tag "city_id", @city_id.to_i %>
        <br /> <br />

        <%= label_tag "mot de passe:" %></br>
        <%= text_field_tag "password", @password %>
        <br /> <br />

        <%= submit_tag "Création de ton profil" %>
        
    <% end %>

        </br>

        <% if @user.errors.any? %>
            <p>Nous n'avons pas réussi à créer le profile pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
                <div class="alert alert-danger" role="alert">
                <li><%= message %></li>
                </div>
        <% end %>
            </ul>

    <% end %>
   
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1> 

<p> Les informations du user
  <li> voici son email : <%= @user.email %> 
  <li> son age : <%= @user.age %>
  <li> sa description : <%= @user.description %>
  <li> le nom de sa ville : <%= @user.city %>

  <%= link_to "Pour les potins lies a sa ville, c'est par ici..." city_path(city_id), class: btn btn-primary %>
  
</p>