config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/', to: 'static_pages#home', as: 'home'
  #get '/welcome/:first_name', to: 'static_pages#welcome', as: 'welcoming'
  #get '/team', to: 'static_pages#team'
  #get '/contact', to: 'static_pages#contact'
  #get '/:potin', to: 'static_pages#potin', as: 'potin'

  resources :welcomes
  resources :teams, only: (:index)
  resources :contacts, only: (:index)
  resources :users, only: [:show, :new, :create]
  resources :gossips
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, 
		presence: true
	validates :zip_code, 
		presence: true,
		uniqueness: true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..14 }
	validates :content, presence: true

	belongs_to :user
	has_many :gossip_tags, dependent: :destroy
	has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :gossip 
	belongs_to :tag 
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip_tags, dependent: :destroy
	has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :password, presence: true, length:{minimum: 6}

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :description, presence: true
	validates :email, presence: true, uniqueness: true,
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	validates :age, presence: true

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	
	def show
		@id = params[:id]
		@city = City.find(params[:id])
		@user_city = @city.name
	end
	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index

	end


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all 
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60


   # binding.pry
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id:11)

    if @gossip.save
      redirect_to gossips_path, notice: "Potin sauvegardé, merci pour ta contribution !"
      puts "Potin sauvegardé"
    else
      puts "La sauvegarde n'a pu être faite. Voici pourquoi :"
      puts @gossip.errors.messages
     render'new', alert: "Le potin n'a pu être sauvegardé, vois pourquoi ds la notification."
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params)
    redirect_to gossips_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    session = User.new
  end
  
  def create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gossips_path
    else
      flash.now[:danger] = 'Combinaison email/mot de passe invalide !'
      render 'new'
    end
  end

  def destroy
    if session.delete(:user_id)
      flash[:danger] = 'Au revoir !'
      redirect_to gossips_path
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

	def index

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new 
	end

	def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60


   # binding.pry
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: params[:city_id], password: params[:password])

    if @user.save
    	puts "Utilisateur sauvegardé"	
      redirect_to gossips_path, notice: "Profil créé, tu vas pouvoir rapporter de nouveaux potins !"
      
    else
      puts "Nous n'avons pas pu créer ton profil. Voici pourquoi :"
      puts @user.errors.messages
     render'new', alert: "Ton profil utilisateur n'a pas pu être sauvegardé, vois pourquoi ds la notification."
    end

  end

	def show
		@user = User.find(params[:id])
		@author_info = Gossip.find(params[:id]).user
		@user_city = @author_info.city.name 
	end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

	def show
		@first_name = params[:first_name]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
    
    def logged_in?
        if session[:user_id].nil?
            return true
        else 
            return false
        end
    end

    def good_user?
        if session[:user_id] == Gossip.find(params[:id]).user_id
            return true
        else
            return false
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>


  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Gossip Project", gossips_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>
        <%if logged_in? == true %>
          <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Log in / Inscription
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="<%=new_session_path %>">Log in</a>
              <a class="dropdown-item" href="<%=new_user_path%>">Inscription</a>
            </div>
          </div>
        <%else%>
          <div class="btn-group">
            
              <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class:"btn btn-outline-primary dropdown-toggle" %>
            
          </div>
        <%end%>
        </li>
       
        <li class="nav-item active">
          <%= link_to "Team", teams_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Contact", contacts_path, class: "nav-link" %>
        </li>
        </ul>
      </div>
    </nav>

    <% flash.each do |type, msg| %>
      <div class="alert alert-success" role="alert">
        <%= msg %>
      </div>
    <% end %>

  </header>

  <body>
    <%= yield %>
  </body>

</html>